import type { UiStrings, UiStringSet } from '@repo/ui'

/**
 * Nhãn giao diện của mẫu 07 — port từ hằng `UI` trong prototype
 * `Home 01 - Nam Du Hill.dc.html`.
 *
 * Kiểu `UiStrings` do `@repo/ui` định nghĩa và cả bốn mẫu cùng thoả — thiếu
 * một nhãn là lỗi biên dịch, không phải ô trống lúc chạy. Dữ liệu nghiệp vụ
 * (tên phòng, giá, lịch trình) vẫn ở `core` và dùng chung (luật R8).
 */

export const ui: UiStringSet<UiStrings> = {
    vi: {
        phoneLabel: 'Hotline / Zalo',
        bookNow: 'Đặt phòng',
        checkIn: 'Ngày nhận phòng',
        checkOut: 'Ngày trả phòng',
        guests: 'Khách / phòng',
        guestsWord: 'khách',
        stayType: 'Hình thức',
        stayRoom: 'Chỉ phòng nghỉ',
        stayCombo2: 'Combo 2N1Đ',
        stayCombo3: 'Combo 3N2Đ',
        search: 'Kiểm tra giá',
        perNight: 'mỗi đêm',
        viewAll: 'Xem tất cả',
        heroImage: 'Ảnh banner full màn hình — resort trên đồi hướng biển Nam Du',
        roomsKicker: 'Phòng',
        roomsTitle: 'Không gian nghỉ dưỡng của bạn',
        roomsSub: 'Sáu hạng phòng từ 26 m² đến 56 m², tất cả đều hướng biển hoặc thung lũng.',
        toursKicker: 'Lịch trình',
        toursTitle: 'Combo trọn gói, không lo lịch trình',
        toursSub: 'Vé tàu khứ hồi, phòng nghỉ và tour đảo trong một lần đặt.',
        fromPrice: 'Giá từ',
        perGuest: 'mỗi khách',
        bookTour: 'Đặt combo này',
        placesKicker: 'Điểm đến',
        placesTitle: '21 hòn đảo, tám điểm không nên bỏ qua',
        placesSub:
            'Từ bãi tắm kín gió đến hải đăng cao nhất Việt Nam — tất cả trong bán kính một chuyến tàu gỗ.',
        diningKicker: 'Nhà hàng & Bar',
        diningTitle: 'Ẩm thực đảo, đánh bắt trong ngày',
        diningSub: 'Hải sản mua trực tiếp từ ghe thuyền và lồng bè Hòn Ngang.',
        transportTitle: 'Cách đến Nam Du',
        transportSub: 'Hai chặng: đường bộ tới Rạch Giá, rồi tàu cao tốc ra đảo.',
        notesTitle: 'Lưu ý trước chuyến đi',
        faqTitle: 'Câu hỏi thường gặp',
        faqSub: 'Những điều khách hay hỏi nhất trước khi đặt.',
        galleryKicker: 'Thư viện ảnh',
        galleryTitle: 'Không gian thực tế tại resort',
        ctaTitle: 'Chọn ngày, phần còn lại để chúng tôi lo.',
        ctaSub: 'Nhắn Zalo hoặc gửi email — chúng tôi xác nhận phòng và vé tàu trong vòng 15 phút.',
        emailUs: 'Gửi email',
        footerAbout: 'Khu nghỉ dưỡng trên đồi hướng biển tại Hòn Củ Tron, quần đảo Nam Du.',
        footerNav: 'Liên kết',
        footerContact: 'Liên hệ',
        footerFollow: 'Theo dõi',
    },
    en: {
        phoneLabel: 'Hotline / Zalo',
        bookNow: 'Book now',
        checkIn: 'Check in',
        checkOut: 'Check out',
        guests: 'Guests / rooms',
        guestsWord: 'guests',
        stayType: 'Stay type',
        stayRoom: 'Room only',
        stayCombo2: '2D1N bundle',
        stayCombo3: '3D2N bundle',
        search: 'Check rates',
        perNight: 'per night',
        viewAll: 'View all',
        heroImage: 'Full-width banner — hillside resort facing the sea, Nam Du',
        roomsKicker: 'Rooms & Suites',
        roomsTitle: 'Your space on the island',
        roomsSub: 'Six room types from 26 m² to 56 m², all facing the sea or the valley.',
        toursKicker: 'Itineraries',
        toursTitle: 'All-in bundles, no planning needed',
        toursSub: 'Return ferry, accommodation and island tour in a single booking.',
        fromPrice: 'From',
        perGuest: 'per guest',
        bookTour: 'Book this bundle',
        placesKicker: 'Destinations',
        placesTitle: "21 islands, eight you shouldn't miss",
        placesSub:
            "From sheltered beaches to one of Vietnam's highest lighthouses — all within one boat ride.",
        diningKicker: 'Wining & Dining',
        diningTitle: 'Island food, caught the same day',
        diningSub: "Seafood bought straight off the boats and Hon Ngang's floating pens.",
        transportTitle: 'Getting to Nam Du',
        transportSub: 'Two legs: overland to Rach Gia, then a speedboat to the island.',
        notesTitle: 'Before you travel',
        faqTitle: 'Frequently asked',
        faqSub: 'What guests ask most before booking.',
        galleryKicker: 'Gallery',
        galleryTitle: 'Real spaces at the resort',
        ctaTitle: 'Pick your dates. We handle the rest.',
        ctaSub: 'Message us on Zalo or send an email — we confirm rooms and ferry tickets within 15 minutes.',
        emailUs: 'Email us',
        footerAbout: 'A hillside resort facing the sea on Hon Cu Tron, Nam Du archipelago.',
        footerNav: 'Links',
        footerContact: 'Contact',
        footerFollow: 'Follow',
    },
}
